DryClean/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from User import urls
from Order import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('User.urls')),
    url(r'^',include('Order.urls')),
]

Order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url(r'^$', views.loginForm, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^items/$', views.items, name='items'),
    url(r'^test/$', views.test, name='test'),
    url(r'^myorders/$', views.myorders, name='myorders'),
    url(r'^myorders/order/(?P<pk>[0-9]+)', views.orderdisplay, name='orderdisplay'),

]

User/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [

    url(r'^signup/', views.UserFormView.as_view(), name='signup'),
]

User/models.py
from django.db import models

# Create your models here.

User/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

User/views.py
from django.shortcuts import render
from User.forms import *
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render,  redirect

# Create your views here.
class UserFormView(View):
    form_class = UserForm
    template_name = 'User/registrationform.html'

    def get(self, request):
        if request.user.is_authenticated():
            return redirect('order:home')
        else:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('order:home')
        return render(request, self.template_name, {'form': form})

User/templates/User/base.html
<!DOCTYPE html>
<html lang="en">
<title> {% block title %}{% endblock %}</title>
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'User/register.css' %}">
    {% block head %}{% endblock %}
</head>
<body>

{% block body %}
{% endblock %}


</body>
</html>

User/templates/User/form.template.html
{% extends 'User/base.html' %}
{% block title %}Signup{% endblock %}
{% block body %}
{% load widget_tweaks %}
{% for field in form %}
    <div class="tag{{ forloop.counter }}">
    <div class="form-group" style="font-size: 20px;">
        <label class="col-md-4 control-label">{{ field.label }}</label>
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
        <span class="input-group-addon"></span>
        <div>{{ field|add_class:"fff"}}</div>
    </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

User/templates/User/registrationform.html
{% extends 'User/base.html' %}
{% block title %}Signup{% endblock %}
{% block head %}
{% endblock %}
{% block body %}

<div class="container" style="margin-top: 5%;">

    <form class="well form-horizontal" action=" " method="post"  id="contact_form">

    {% csrf_token %}

<!-- Form Name -->
<legend><b>Sign Up For Free!</b></legend>
{% include 'User/form.template.html' %}
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
    <button type="submit" class="btn btn-warning" >Submit <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>
    <div class="alreadyacc">
        <h5>Already have an account?<a href="{% url 'order:login' %}"> Login..</a> </h5>
     </div>

</form>
</div>
<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright text-muted small">Copyright &copy; DryClean Inc. 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}