DryClean/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from User import urls
from Order import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('User.urls')),
    url(r'^',include('Order.urls')),
]

Order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url(r'^$', views.loginForm, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^items/$', views.items, name='items'),
    url(r'^test/$', views.test, name='test'),
    url(r'^myorders/$', views.myorders, name='myorders'),
    url(r'^myorders/order/(?P<pk>[0-9]+)', views.orderdisplay, name='orderdisplay'),

]

User/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [

    url(r'^signup/', views.UserFormView.as_view(), name='signup'),
]

Order/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class DeliverTo(models.Model):
    options = models.CharField(max_length=100)

    def __str__(self):
        return (self.options)

class Category(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.category_name)


class Items(models.Model):
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.CharField(max_length=50)
    rate = models.IntegerField()

    def __str__(self):
        return (self.category_id.category_name)+"-"+(self.type)

class OrderInfo(models.Model):
    pickup_date = models.CharField(max_length=100,null=True)
    pickup_time = models.CharField(max_length=100,null=True)
    pickup_add = models.CharField(max_length=100,null=True)
    pickup_city = models.CharField(max_length=100,null=True)
    pickup_pin = models.CharField(max_length=100,null=True)
    del_date = models.CharField(max_length=100,null=True)
    del_time = models.CharField(max_length=100,null=True)
    del_add = models.CharField(max_length=100,null=True)
    del_city = models.CharField(max_length=100,null=True)
    del_pin = models.CharField(max_length=100,null=True)
    del_option = models.ForeignKey(DeliverTo, on_delete=models.CASCADE, null=True)
    total_fare = models.IntegerField(null=True)

    def __str__(self):
        return str(self.id)


class OrderItems(models.Model):
    order_info_id = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=10, null=True)

    def __str__(self):
        return str(self.id)


class OrderPlaced(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    order_info_id = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    order_date = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.user_id.pk)+"-"+str(self.order_info_id.pk)

Order/forms.py
from django.contrib.auth.models import User
from django import forms

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

Order/views.py
from django.shortcuts import render,HttpResponse,render_to_response
from django.views.generic import View
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render,  redirect
from .models import *
import datetime
import json
from time import gmtime, strftime, localtime


# Create your views here.
def loginForm(request):
    if request.user.is_authenticated():
        return redirect('order:home')

    if(request.method=="POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('order:home')
        return HttpResponse('<p>Sorry ! Your Username and Password dont match.</p>')


    return render(request,'Order/login.html',{})


def logout_view(request):
    logout(request)
    return redirect('order:login')


def home(request):
    if request.user.is_authenticated():
        name = request.user.username
        name = name.title()
        cat = Category.objects.all()
        return render(request, 'Order/homepage.html', {'name': name , 'cat': cat })
    else:
        return redirect('order:login')


def items(request):
    if (request.method == "POST"):
        cat = request.POST.getlist('options')
        item_dict={}
        deliver_to = DeliverTo.objects.all()
        orderplaced = OrderPlaced.objects.filter(user_id=request.user.pk)
        flag = 1
        if not orderplaced:
            flag = 0
        for c in cat:
            cat_obj = Category.objects.get(category_name=c)
            item_dict[c]=[]
            d = Items.objects.filter(category_id=cat_obj.pk)
            for i in d:
                item_dict[c].append(i)
        return render(request, 'Order/items.html', {'cat_list':cat, 'name': request.user.username.title(),
                                                    'deliver_to': deliver_to, 'item_dict':item_dict, 'flag':flag,
                                                    'orders':orderplaced})
    else:
        return HttpResponse("not valid")


def test(request):
    if request.is_ajax():
        x = request.POST['items_obj']
        it = json.loads(x)
        print(it)

        z = request.POST['pick_obj']
        pu = json.loads(z)
        print(pu)

        p = request.POST['del_obj']
        de = json.loads(p)
        print(de)

        tot_fare = 0
        del_opt = DeliverTo.objects.get(id=de['option'])

        if(pu['add_id'] != ""):
            z = OrderInfo.objects.get(id=pu['add_id'])
            pu['address']=z.pickup_add
            pu['city']=z.pickup_city
            pu['pincode']=z.pickup_pin

        if(de['same'] == "1"):
            de['address']=pu['address']
            de['city']=pu['city']
            de['pincode']=pu['pincode']

        order_info = OrderInfo()                  #making orderinfo
        order_info.pickup_date = pu['date']
        order_info.pickup_time = pu['time']
        order_info.pickup_add = pu['address']
        order_info.pickup_city = pu['city']
        order_info.pickup_pin = pu['pincode']
        order_info.del_date = de['date']
        order_info.del_time = de['time']
        order_info.del_add = de['address']
        order_info.del_city = de['city']
        order_info.del_pin = de['pincode']
        order_info.del_option = del_opt
        order_info.save()

        for key,value in it.items():
            item = Items.objects.get(id=key)
            order_items = OrderItems()
            order_items.order_info_id = order_info
            order_items.items = item
            order_items.quantity = value
            tot_fare = tot_fare + (int(value)*(item.rate))
            order_items.save()

        order_info1 = OrderInfo.objects.get(pk=order_info.pk)
        order_info1.total_fare = tot_fare
        order_info1.save()

        orderplaced = OrderPlaced()
        orderplaced.user_id = request.user
        orderplaced.order_info_id = order_info
        orderplaced.order_date = strftime("%Y-%m-%d %H:%M:%S", localtime())
        orderplaced.save()

        items_ordered = OrderItems.objects.filter(order_info_id=order_info.pk)

        return render_to_response('Order/placed_order.html', {'order_info':order_info1,'items':items_ordered,
                                                              'date':orderplaced.order_date})


def myorders(request):
    order_placed = OrderPlaced.objects.filter(user_id=request.user.pk)
    return render(request, 'Order/myorders.html', {'orders':order_placed, 'name': request.user.username.title()})


def orderdisplay(request, pk):
    if request.user.is_authenticated():
        orderplaced = OrderPlaced.objects.get(order_info_id=pk)
        if(request.user == orderplaced.user_id):
            order_info = OrderInfo.objects.get(pk=pk)
            items_ordered = OrderItems.objects.filter(order_info_id=pk)

            return render(request, 'Order/placed_order.html', {'order_info': order_info, 'items': items_ordered,
                                                               'date': orderplaced.order_date})
        else:
            return HttpResponse("Order Not Found!")
    else:
        return render(request, 'Order/login.html', {})

Order/templates/Order/delivery.html
{% load staticfiles %}
<script type="text/javascript" src="{% static 'Order/final.js' %}"></script>
<script type="text/javascript" src="{% static 'Order/del.js' %}"></script>
<script type="text/javascript" src="{% static 'Order/radios_schedule_del.js' %}"></script>


<div class="container delivery" id="delivery" style="display: none; text-align: center;">
    <div style="border-bottom: thin solid; margin-bottom: 2%;"><h2>Delivery Time</h2></div>

    <div class="form-group text-center">
    <label for="usr">Date: </label>
    <input type="date" class="form-control" id="del_date" style="width: 20%; display: inline;">
    </div>

    <div class="form-group">
    <label for="sel1">Time:</label>
    <select class="form-control" id="del_time" style="display: inline; width: 20%;">
    <option value="">select time</option>
    <option value="Morning 7am - 9am">Morning 7am - 9am</option>
    <option value="Noon 2pm - 4pm">Noon 2pm - 4pm</option>
    <option value="Evening 5pm - 9pm">Evening 5pm - 9pm</option>
    </select>
    </div>
    <br>
    <div style="border-bottom: thin solid; margin-bottom: 2%;"><h2>Delivery Location</h2></div>
    <div class="form-group text-center">
    <input type="radio" name="del_select" id="add_select_del1"><b>Use Same As Pickup Location</b>
    </div>

    <input type="radio" name="del_select" id="add_select_del2"><b>Enter New Delivery Address</b>
    <div class="new_add_del">
    <div class="form-group text-center">
    <label for="usr">Address: </label>
    <input type="text" class="form-control" id="del_loc1" style="width: 20%; display: inline;">
    </div>
    <div class="form-group text-center">
    <label for="usr">City: </label>
    <input type="text" class="form-control" id="del_loc2" style="width: 20%; display: inline;">
    </div>
    <div class="form-group text-center">
    <label for="usr">Pincode: </label>
    <input type="text" class="form-control" id="del_loc3" style="width: 20%; display: inline;">
    </div>
    </div>

    <div class="Options">
    <br>
        <b>Possible Option</b>
        <form>
    {% for op in deliver_to %}
    <div class="radio">
        <label><input type="radio" name="optradio" value="{{ op.id }}">{{ op.options }}</label>
    </div>
    {% endfor %}
        </form>
    </div>


    {% csrf_token %}
    <button type="submit" id="save_del">Save</button>
    <button type="submit" id="all_obj" href="{% url 'order:test' %}">Place Your Order</button>



</div>

    <div class="container text-center" id="caption">
        <h1>Congratulations !</h1>
        <h3>Your order has successfully been placed</h3>
  </div>
  <div id="order_placed">

  </div>

Order/templates/Order/homepage.html
{% extends 'User/base.html' %}

{% block title %}DryClean | Home{% endblock %}

{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Order/home.css' %}">
    <script type="text/javascript" src="{% static 'Order/check_box.js' %}"></script>
{% endblock %}

{% block body %}


<div class="jumbotron text-center" style="background-color: lightcoral; padding:0 0 5% 0;  width: auto;">
  {% include 'Order/nav.html' %}
  <h1>Get Your Clothes Clean</h1>
  <p>Place your order for picking your laundry from your doorstep and get a hassle-free delivery with full satisfaction.</p>
</div>

<div class="category col-sm-12">
    <div class="container text-center">
    <h2>Select Category</h2>
    <form action="{% url 'order:items' %}" method="post">
    {% csrf_token %}
            <div id="boom">
            {% for c in cat %}
                <div class="row">
                    <div class="col-sm-6">{{ c.category_name }}</div>
                    <div class="col-sm-6"><label class="btn btn-default">
				        <input type="checkbox" class="check" name="options" value={{ c.category_name }} autocomplete="off">
                        </label>
                    </div>
                </div>
            {% endfor %}
            </div>

        <div class="row">
            <input type="submit" id="proceed" value="Proceed">
        </div>
    </form>
    </div>
</div>

{% endblock %}

Order/templates/Order/items.html
{% extends 'User/base.html' %}

{% block title %} DryClean | Items {% endblock %}

{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Order/item_style.css' %}">
    <script type="text/javascript" src="{% static 'Order/to_place.js' %}"></script>
{% endblock %}

{% block body %}
    {% include 'Order/nav.html' %}
    {% include 'Order/schedule.html' %}
    <div class="choose" id="choose">
    <div class="row text-center">
    <h2>Choose Your Items</h2>
    </div>
    <nav class="navbar navbar-default col-sm-offset-1 col-sm-10" id="item_nav">
    <div class="container-fluid" id="item_bar">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myItembar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><b>Items</b></a>
    </div>
    <div class="collapse navbar-collapse" id="myItembar">
      <ul class="nav navbar-nav">
        {% for c in cat_list %}
            <script type="text/javascript">
            $(document).ready(function(){
                $('#type{{ cat_list.0 }}').show();
                window.xp = "{{ cat_list.0 }}";
                $('#item{{ c }}').click(function(){
                //alert(window.x);
                $('#type'+window.xp).hide();
                $('#type{{ c }}').show();
                window.xp = "{{ c }}";
            });
            });
            </script>
            <li><a href="#" id="item{{ c }}">{{ c }}</a></li>

        {% endfor %}
      </ul>
          </div>
    </div>
  </nav>

{% for key,value in item_dict.items %}
        {% if key in cat_list %}
            <div class="container" id="type{{ key }}" style="display: none;">
                {% for x in value %}
                <script type="text/javascript">
                $(document).ready(function(){
                        window.obj={};                        //global variable
                       $(".press{{ x.id }}").click(function(){
                           var but_val = $(this).val();
                           obj['{{ x.id }}']=0;
                           var value;
                           if(but_val=="plus") {
                               value = parseInt($('#quant{{ x.id }}').val());
                               value = value + 1;
                           }
                           else{
                               value = parseInt($('#quant{{ x.id }}').val());
                               if(value>0)
                               value = value - 1;
                           }
                           $('#quant{{ x.id }}').val(value);
                           if(value>0)
                                obj['{{ x.id }}'] = value;
                           else
                                delete obj['{{ x.id }}'];
                           console.log(obj);
                        });
                        });
                    </script>

                <div class="boxes col-sm-offset-1 col-sm-10 col-xs-offset-2 col-xs-10">
                <h4><b>{{ x.type }}</b></h4>
                <p style="font-size: small; color: lightslategrey;">Cost Per Piece: Rs. {{ x.rate }}</p>

                <div class="box2">
                <button type="button" class="btn btn-default press{{ x.id }}" value="minus"><span class="glyphicon glyphicon-minus-sign"></span></button>
                <input type="text" id="quant{{ x.id }}" value="0" style="width: 20%; text-align: center;" disabled>
                <button type="button" class="btn btn-default press{{ x.id }}" value="plus"><span class="glyphicon glyphicon-plus-sign"></span></button>
                </div>

                </div>
            {% endfor %}
            </div>
        {% endif %}
{% endfor %}

    <button type="submit" id="next1" href="#" class="col-sm-offset-6 col-xs-offset-6">Next</button>
    </div>

{% endblock %}

Order/templates/Order/login.html
{% extends 'User/base.html' %}
{% block title %} DryClean {% endblock %}
{% block body %}
    <div class="container col-sm-offset-4 col-sm-4">
        <div class="well">
            <form class="form-horizontal" method="post" action="">
                {% csrf_token %}
              <div class="form-group">
                <label class="control-label col-sm-2" for="email">Username:</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="user" name="username" placeholder="Enter username">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">Password:</label>
                <div class="col-sm-10">
                  <input type="password" class="form-control" id="pwd" name="password" placeholder="Enter password">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">Submit</button>
                </div>
              </div>
            </form>
        </div>
    <p>Not a member? <a href="{% url 'user:signup' %}">Sign Up</a></p>
    </div>


{% endblock %}

Order/templates/Order/myorders.html
{% include 'User/base.html' %}
{% include 'Order/nav.html' %}
<div class="container text-center" style="font-size: 18px;">
<table class="table table-condensed text-left">
    <thead>
        <tr>
            <th>Serial Number</th>
            <th>Order Number</th>
            <th>Order Date</th>
        </tr>
    </thead>
    <tbody>

    {% for i in orders %}
        <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'order:orderdisplay' i.order_info_id  %}">{{ i.order_info_id }}</a></td>
        <td>{{ i.order_date }}</td>
        </tr>
    {% endfor %}

    </tbody>
</table>
</div>

Order/templates/Order/nav.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DryClean</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'order:home' %}">Home</a></li>
        <li><a href="{% url 'order:myorders' %}">My Orders</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <div class="dropdown" style="padding: 8px;">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" style="background-color: transparent; border: none;"><span class="glyphicon glyphicon-user"></span>
                {{ name }} <span class="caret"></span></button>
                    <ul class="dropdown-menu text-center">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="{% url 'order:logout' %} ">Logout</a></li>
                    </ul>
          </div>

      </ul>
    </div>
  </div>
  </nav>

Order/templates/Order/placed_order.html
{% extends 'user/base.html' %}
{% block body %}
<div class="container text-center">
<h4>Order Details</h4>

<table class="table table-condensed text-left">
    <tbody>
        <tr>
            <td><b>Order Ref No.</b></td>
            <td>{{ order_info.id }}</td>
        </tr>
        <tr>
            <td><b>Order Date</b></td>
            <td>{{ date }}</td>
        </tr>
    </tbody>
</table>

<table class="table table-condensed text-left">
    <thead>
    <tr>
        <th>
            Laundry Items
        </th>
    </tr>
    </thead>

    <thead>
      <tr>
        <th>Items</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
    {% for x in items %}
      <tr>
        <td>{{ x.items.type }}</td>
        <td>{{ x.quantity }}</td>
      </tr>
    {% endfor %}
        <tr>
        <td><b>Total Fare</b></td>
        <td><b>Rs. {{ order_info.total_fare }}</b></td>
        </tr>
    </tbody>
</table>
<br>
<table class="table table-condensed text-left">
    <thead>
    <tr>
        <th>
            Location Details
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Pickup Location</td>
        <td>{{ order_info.pickup_add }} {{ order_info.pickup_city }} {{ order_info.pickup_pin }}</td>
    </tr>
    <tr>
        <td>Pickup Date-Time</td>
        <td>{{ order_info.pickup_date }} {{ order_info.pickup_time }} </td>
    </tr>
    <tr>
        <td>Delivery Location</td>
        <td>{{ order_info.del_add }} {{ order_info.del_city }} {{ order_info.del_pin }}</td>
    </tr>
    <tr>
        <td>Delivery Date-Time</td>
        <td>{{ order_info.del_date }} {{ order_info.del_time }} </td>
    </tr>
    <tr>
        <td>Deliver To</td>
        <td>{{ order_info.del_option }} </td>
    </tr>
   </tbody>
</table>
<a href="{% url 'order:home' %}">Go To Home</a>
</div>
{% endblock %}

Order/templates/Order/schedule.html
{% load staticfiles %}
<script type="text/javascript" src="{% static 'Order/pickup.js' %}"></script>
<script type="text/javascript" src="{% static 'Order/to_delivery.js' %}"></script>
<script type="text/javascript" src="{% static 'Order/radios_schedule.js' %}"></script>

{% include 'Order/delivery.html'%}


<div class="container schedule" id="schedule" style="display: none; text-align: center;">
    <div style="border-bottom: thin solid; margin-bottom: 2%;"><h2>Pickup Time</h2></div>

    <div class="form-group text-center">
    <label for="usr">Date: </label>
    <input type="date" class="form-control" id="pickup_date" min="{% now "Y-m-d" %}" style="width: 20%; display: inline;">
    </div>

    <div class="form-group">
    <label for="sel1">Time:</label>
    <select class="form-control" id="pickup_time" style="display: inline; width: 20%;">
    <option value="">select time</option>
    <option value="Morning 7am - 9am">Morning 7am - 9am</option>
    <option value="Noon 2pm - 4pm">Noon 2pm - 4pm</option>
    <option value="Evening 5pm - 9pm">Evening 5pm - 9pm</option>
    </select>
    </div>
    <br>
    <div style="border-bottom: thin solid; margin-bottom: 2%;"><h2>Pickup Location</h2></div>
    <div class="form-group text-center">
    {% if flag == 1 %}
    <input type="radio" name="add_select1" id="add_select1">Saved Address
        <div class="saved_add">
            <select class="form-control" id="pickup_saved" style="display: inline; width: 20%;">
            <option value="">select address</option>
            {% for x in orders %}
            <option value="{{ x.order_info_id }}">{{ x.order_info_id.pickup_add }}</option><br>
            {% endfor %}
            </select>
        </div>
    {% endif %}
    </div>

    <input type="radio" name="add_select2" id="add_select2">Enter New Address
    <div class="new_add">

    <div class="form-group text-center">
    <label for="usr">Address: </label>
    <input type="text" class="form-control" id="pickup_loc1" style="width: 20%; display: inline;">
    </div>

    <div class="form-group text-center">
    <label for="usr">City: </label>
    <input type="text" class="form-control" id="pickup_loc2" style="width: 20%; display: inline;">
    </div>

    <div class="form-group text-center">
    <label for="usr">Pincode: </label>
    <input type="text" class="form-control" id="pickup_loc3" style="width: 20%; display: inline;">
    </div>

    </div>

    <br>
    <button type="submit" id="back">Back</button>
    <button type="submit" id="save_pick">Save</button>
    <button type="submit" id="next2">Next</button>

</div>